# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    csrf_protection: true

    rate_limiter:
        forgot_password:
            policy: sliding_window
            limit: 3
            interval: '15 minutes'

    http_client:
        scoped_clients:
            sumup.client:
                base_uri: 'https://api.sumup.com'
                headers:
                    Accept: 'application/json'
                timeout: 20

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        cache:
            app: cache.adapter.array
        session:
            storage_factory_id: session.storage.factory.mock_file
